# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftStars' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftStars
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'

  target 'SwiftStarsTests' do
    inherit! :search_paths

    pod 'Quick' , '~> 1.3.2'
    pod 'Nimble' , '~> 7.3.1'
    pod 'iOSSnapshotTestCase' , '~> 4.0.0'
    pod 'KIF', :configurations => ['Debug']
  end

  target 'SwiftStarsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
